### ISSUE TITLE
Passenger support

### ISSUE THREAD

**Issue by Yuav** [unibet/puppet-forge-server#1]
Want to run this behind Apache

**Comment by craiggenner** [comment]
This no longer works as `build` requires 2 arguments:
     def build(backends, webui_root)

Any ideas how to fix this as :- 
un PuppetForgeServer::Server.new.build(backends, webui_root)
doesn't work

**Comment by i11** [comment]
Ah... totally forgot about this use-case.  Try doing
```
run PuppetForgeServer::Server.new.build(backends, PuppetForgeServer::Utils::OptionParser.class_eval('@@DEFAULT_WEBUI_ROOT'))
```

**Comment by craiggenner** [comment]
No luck - `Internal Server Error`

and:
```
App 19324 stderr: [ 2015-06-18 11:23:48.6417 19351/0x000000025f2650(Worker 1) utils.rb:68 ]: *** Exception NameError in Rack application object (uninitialized constant Rack::Request::QUERY_STRING) (process 19351, thread 0x000000025f2650(Worker 1)):
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-1.6.2/lib/rack/request.rb:24:in `query_string'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-1.6.2/lib/rack/request.rb:188:in `GET'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-1.6.2/lib/rack/request.rb:230:in `params'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:901:in `call!'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-1.6.2/lib/rack/commonlogger.rb:33:in `call'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-1.6.2/lib/rack/logger.rb:15:in `call'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-1.6.2/lib/rack/commonlogger.rb:33:in `call'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-1.6.2/lib/rack/head.rb:13:in `call'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:68:in `optimized_each'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
App 19324 stderr:       from /var/lib/gems/1.9.1/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
App 19324 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
App 19324 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:142:in `accept_and_process_next_request'
App 19324 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 19324 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'
```

**Comment by i11** [comment]
Hmm.. weird, it worked for me with passenger 4.0.53 and apache 2.4.6. What kind of setup do you have? I could try to reproduce it.

**Comment by craiggenner** [comment]
apache 2.4.7-1ubuntu4.4 and passenger 4.0.37-2

This is a Ubuntu 14.04.2 LTS

**Comment by i11** [comment]
I was able to reproduce it. Apparently rack gem has to be downgraded. I'll pin it in the gemspec and release a bit later today.

**Comment by i11** [comment]
Try something like 1.4.5 if you're anxious.

**Comment by craiggenner** [comment]
Thanks, I'll wait until it has been released since I just end up fighting gem versions as soon as I try and use 1.4.5.

**Comment by i11** [comment]
1.5.3 released. Please give it a go and let me know the results.

**Comment by craiggenner** [comment]
Thanks, that works.

I'll do a merge request to update the readme.

Appreciate the quick response on this, it really helps.

**Comment by i11** [comment]
Sure thing. Glad I could help.
